<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Regiones;
use App\Models\Ciudades;
use App\Models\Comunas;
use App\Models\Estados;
use App\Models\Perfil;
use App\Models\TipoRequerimiento;
use App\Models\Comentarios;
use App\User;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        Perfil::create(['id_perfil'=>1,'perfil'=>'ADMINISTRADOR PLATAFORMA','estado'=>1]);
        Perfil::create(['id_perfil'=>2,'perfil'=>'BODEGA PRODUCTOS','estado'=>1]);
        Perfil::create(['id_perfil'=>3,'perfil'=>'ORDEN SERVICIO','estado'=>1]);
        Perfil::create(['id_perfil'=>4,'perfil'=>'CLIENTE','estado'=>1]);

        User::create(['name' => 'ADMIN','email' => 'admin@test.cl','estado' => '1','id_perfil' => '1','password' => bcrypt('asdf123')]);
        User::create(['name' => 'BODEGA DEMO','email' => 'bodega@test.cl','estado' => '1','id_perfil' => '2','password' => bcrypt('asdf123')]);
        User::create(['name' => 'ORDEN DEMO','email' => 'orden@test.cl','estado' => '1','id_perfil' => '3','password' => bcrypt('asdf123')]);
        User::create(['name' => 'CLIENTE DEMO','email' => 'cliente@test.cl','estado' => '1','id_perfil' => '4','password' => bcrypt('asdf123')]);
        
        Estados::create(['id_estado'=>1,'estado'=>"Autorizado"]);
        Estados::create(['id_estado'=>2,'estado'=>"En Ruta"]);
        Estados::create(['id_estado'=>3,'estado'=>"Pendiente de Stock"]);
        Estados::create(['id_estado'=>4,'estado'=>"Stan By"]);
        Estados::create(['id_estado'=>5,'estado'=>"Cancelado"]);
        Estados::create(['id_estado'=>6,'estado'=>"Finalizado"]);
        Estados::create(['id_estado'=>7,'estado'=>"En Produccion"]);

        TipoRequerimiento::create(['id_tipo_requerimiento'=>1,'requerimiento'=>'Distribucion','estado'=>1]);
        TipoRequerimiento::create(['id_tipo_requerimiento'=>2,'requerimiento'=>'Retiro','estado'=>1]);
        TipoRequerimiento::create(['id_tipo_requerimiento'=>3,'requerimiento'=>'Reparacion','estado'=>1]);
        TipoRequerimiento::create(['id_tipo_requerimiento'=>4,'requerimiento'=>'Implementacion','estado'=>1]);
        TipoRequerimiento::create(['id_tipo_requerimiento'=>5,'requerimiento'=>'Levantamiento','estado'=>1]);
        TipoRequerimiento::create(['id_tipo_requerimiento'=>6,'requerimiento'=>'Remodelacion','estado'=>1]);
        TipoRequerimiento::create(['id_tipo_requerimiento'=>7,'requerimiento'=>'Fabricacion','estado'=>1]);
        TipoRequerimiento::create(['id_tipo_requerimiento'=>8,'requerimiento'=>'Campaña','estado'=>1]);
        TipoRequerimiento::create(['id_tipo_requerimiento'=>9,'requerimiento'=>'Otros','estado'=>1]);

        Regiones::create(['region' => "Tarapacá",'shortname' => 'I']);
        Regiones::create(['region' => "Antofagasta",'shortname' => 'II']);
        Regiones::create(['region' => "Atacama",'shortname' => 'III']);
        Regiones::create(['region' => "Coquimbo",'shortname' => 'IV']);
        Regiones::create(['region' => "Valparaíso",'shortname' => 'V']);
        Regiones::create(['region' => "Libertador Gral. Bernardo O'higgins",'shortname' => 'VI']);
        Regiones::create(['region' => "Maule",'shortname' => 'VII']);
        Regiones::create(['region' => "BioBio",'shortname' => 'VIII']);
        Regiones::create(['region' => "Araucania",'shortname' => 'IX']);
        Regiones::create(['region' => "Los Lagos",'shortname' => 'X']);
        Regiones::create(['region' => "Aysén del Gral. Carlos Ibáñez del Campo",'shortname' => 'XI']);
        Regiones::create(['region' => "Magallanes",'shortname' => 'XII']);
        Regiones::create(['region' => "Metropolitana",'shortname' => 'RM']);
        Regiones::create(['region' => "Los Ríos",'shortname' => 'XIV']);
        Regiones::create(['region' => "Arica y Parinacota",'shortname' => 'XV']);
        Regiones::create(['region' => "Ñuble",'shortname' => 'XVI']);


        Ciudades::create(['ciudad' => "Iquique", 'id_region' => 1,'capital'=>'Iquique']);
        Ciudades::create(['ciudad' => "Tamarugal", 'id_region' => 1,'capital'=>'Pozo Almonte']);
        Ciudades::create(['ciudad' => "Antofagasta", 'id_region' => 2,'capital'=>'Antofagasta']);
        Ciudades::create(['ciudad' => "El Loa", 'id_region' => 2,'capital'=>'Calama']);
        Ciudades::create(['ciudad' => "Tocopilla", 'id_region' => 2,'capital'=>'Tocopilla']);
        Ciudades::create(['ciudad' => "Copiapo", 'id_region' => 3,'capital'=>'Copiapo']);
        Ciudades::create(['ciudad' => "Chañaral", 'id_region' => 3,'capital'=>'Chañaral']);
        Ciudades::create(['ciudad' => "Huasco", 'id_region' => 3,'capital'=>'Vallenar']);
        Ciudades::create(['ciudad' => "Elqui", 'id_region' => 4,'capital'=>'Coquimbo']);
        Ciudades::create(['ciudad' => "Choapa", 'id_region' => 4,'capital'=>'Illapel']);
        Ciudades::create(['ciudad' => "Limarí", 'id_region' => 4,'capital'=>'Ovalle']);
        Ciudades::create(['ciudad' => "Valparaíso", 'id_region' => 5,'capital'=>'Valparaíso']);
        Ciudades::create(['ciudad' => "Isla de Pascua", 'id_region' => 5,'capital'=>'Hanga Roa']);
        Ciudades::create(['ciudad' => "Los Andes", 'id_region' => 5,'capital'=>'Los Andes']);
        Ciudades::create(['ciudad' => "Petorca", 'id_region' => 5,'capital'=>'La Ligua']);
        Ciudades::create(['ciudad' => "Quillota", 'id_region' => 5,'capital'=>'Quillota']);
        Ciudades::create(['ciudad' => "San Antonio", 'id_region' => 5,'capital'=>'San Antonio']);
        Ciudades::create(['ciudad' => "San Felipe de Aconcagua", 'id_region' => 5,'capital'=>'San Felipe']);
        Ciudades::create(['ciudad' => "Cachapoal", 'id_region' => 6,'capital'=>'Rancagua']);
        Ciudades::create(['ciudad' => "Cardenal Caro", 'id_region' => 6,'capital'=>'Pichilemu']);
        Ciudades::create(['ciudad' => "Colchagua", 'id_region' => 6,'capital'=>'San Fernando']);
        Ciudades::create(['ciudad' => "Talca", 'id_region' => 7,'capital'=>'Talca']);
        Ciudades::create(['ciudad' => "Cauquenes", 'id_region' => 7,'capital'=>'Cauquenes']);
        Ciudades::create(['ciudad' => "Curicó", 'id_region' => 7,'capital'=>'Curicó']);
        Ciudades::create(['ciudad' => "Linares", 'id_region' => 7,'capital'=>'Linares']);
        Ciudades::create(['ciudad' => "Concepción", 'id_region' => 8,'capital'=>'Concepción']);
        Ciudades::create(['ciudad' => "Arauco", 'id_region' => 8,'capital'=>'Lebu']);
        Ciudades::create(['ciudad' => "Biobio", 'id_region' => 8,'capital'=>'Los Ángeles']);
        Ciudades::create(['ciudad' => "Cautin", 'id_region' => 9,'capital'=>'Temuco']);
        Ciudades::create(['ciudad' => "Malleco", 'id_region' => 9,'capital'=>'Angol']);
        Ciudades::create(['ciudad' => "Llanquihue", 'id_region' => 10,'capital'=>'Puerto Montt']);
        Ciudades::create(['ciudad' => "Chiloe", 'id_region' => 10,'capital'=>'Castro']);
        Ciudades::create(['ciudad' => "Osorno", 'id_region' => 10,'capital'=>'Osorno']);
        Ciudades::create(['ciudad' => "Palena", 'id_region' => 10,'capital'=>'Chaitén']);
        Ciudades::create(['ciudad' => "Coyhaique", 'id_region' => 11,'capital'=>'Coyhaique']);
        Ciudades::create(['ciudad' => "Aysén", 'id_region' => 11,'capital'=>'Puerto Aysén']);
        Ciudades::create(['ciudad' => "Capitan Prat", 'id_region' => 11,'capital'=>'Cochrane']);
        Ciudades::create(['ciudad' => "General Carrera", 'id_region' => 11,'capital'=>'Chile Chico']);
        Ciudades::create(['ciudad' => "Magallanes", 'id_region' => 12,'capital'=>'Punta Arenas ']);
        Ciudades::create(['ciudad' => "Antártica Chilena", 'id_region' => 12,'capital'=>'Puerto Williams']);
        Ciudades::create(['ciudad' => "Tierra del Fuego", 'id_region' => 12,'capital'=>'Porvenir']);
        Ciudades::create(['ciudad' => "Última Esperanza", 'id_region' => 12,'capital'=>'Puerto Natales']);
        Ciudades::create(['ciudad' => "Santiago", 'id_region' => 13,'capital'=>'Santiago']);
        Ciudades::create(['ciudad' => "Cordillera", 'id_region' => 13,'capital'=>'Puente Alto']);
        Ciudades::create(['ciudad' => "Chacabuco", 'id_region' => 13,'capital'=>'Colina']);
        Ciudades::create(['ciudad' => "Maipo", 'id_region' => 13,'capital'=>'San Bernardo']);
        Ciudades::create(['ciudad' => "Melipilla", 'id_region' => 13,'capital'=>'Melipilla']);
        Ciudades::create(['ciudad' => "Talagante", 'id_region' => 13,'capital'=>'Talagante']);
        Ciudades::create(['ciudad' => "Valdivia", 'id_region' => 14,'capital'=>'Valdivia']);
        Ciudades::create(['ciudad' => "Ranco", 'id_region' => 14,'capital'=>'La Unión']);
        Ciudades::create(['ciudad' => "Arica", 'id_region' => 15,'capital'=>'Arica']);
        Ciudades::create(['ciudad' => "Parinacota", 'id_region' => 15,'capital'=>'Putre']);
        Ciudades::create(['ciudad' => "Itata", 'id_region' => 16,'capital'=>'Quirihue']);
        Ciudades::create(['ciudad' => "Diguillín", 'id_region' => 16,'capital'=>'Bulnes']);
        Ciudades::create(['ciudad' => "Punilla", 'id_region' => 16,'capital'=>'San Carlos']);


        Comunas::create(['comuna' => "Iquique", 'id_ciudad' => 1, 'id_region' => 1]);
        Comunas::create(['comuna' => "Alto Hospicio", 'id_ciudad' => 1, 'id_region' => 1]);
        Comunas::create(['comuna' => "Pozo Almonte", 'id_ciudad' => 2, 'id_region' => 1]);
        Comunas::create(['comuna' => "Camiña", 'id_ciudad' => 2, 'id_region' => 1]);
        Comunas::create(['comuna' => "Colchane", 'id_ciudad' => 2, 'id_region' => 1]);
        Comunas::create(['comuna' => "Huara", 'id_ciudad' => 2, 'id_region' => 1]);
        Comunas::create(['comuna' => "Pica", 'id_ciudad' => 2, 'id_region' => 1]);
        Comunas::create(['comuna' => "Antofagasta", 'id_ciudad' => 3, 'id_region' => 2]);
        Comunas::create(['comuna' => "Mejillones", 'id_ciudad' => 3, 'id_region' => 2]);
        Comunas::create(['comuna' => "Sierra Gorda", 'id_ciudad' => 3, 'id_region' => 2]);
        Comunas::create(['comuna' => "Taltal", 'id_ciudad' => 3, 'id_region' => 2]);
        Comunas::create(['comuna' => "Calama", 'id_ciudad' => 4, 'id_region' => 2]);
        Comunas::create(['comuna' => "Ollague", 'id_ciudad' => 4, 'id_region' => 2]);
        Comunas::create(['comuna' => "San Pedro de Atacama", 'id_ciudad' => 4, 'id_region' => 2]);
        Comunas::create(['comuna' => "Tocopilla", 'id_ciudad' => 5, 'id_region' => 2]);
        Comunas::create(['comuna' => "María Elena", 'id_ciudad' => 5, 'id_region' => 2]);
        Comunas::create(['comuna' => "Copiapó", 'id_ciudad' => 6, 'id_region' => 3]);
        Comunas::create(['comuna' => "Caldera", 'id_ciudad' => 6, 'id_region' => 3]);
        Comunas::create(['comuna' => "Tierra Amarilla", 'id_ciudad' => 6, 'id_region' => 3]);
        Comunas::create(['comuna' => "Chañaral", 'id_ciudad' => 7, 'id_region' => 3]);
        Comunas::create(['comuna' => "Diego de Almagro", 'id_ciudad' => 7, 'id_region' => 3]);
        Comunas::create(['comuna' => "Vallenar", 'id_ciudad' => 8, 'id_region' => 3]);
        Comunas::create(['comuna' => "Alto del Carmen", 'id_ciudad' => 8, 'id_region' => 3]);
        Comunas::create(['comuna' => "Freirina", 'id_ciudad' => 8, 'id_region' => 3]);
        Comunas::create(['comuna' => "Huasco", 'id_ciudad' => 8, 'id_region' => 3]);
        Comunas::create(['comuna' => "La Serena", 'id_ciudad' => 9, 'id_region' => 4]);
        Comunas::create(['comuna' => "Coquimbo", 'id_ciudad' => 9, 'id_region' => 4]);
        Comunas::create(['comuna' => "Andacollo", 'id_ciudad' => 9, 'id_region' => 4]);
        Comunas::create(['comuna' => "La Higuera", 'id_ciudad' => 9, 'id_region' => 4]);
        Comunas::create(['comuna' => "Paihuano", 'id_ciudad' => 9, 'id_region' => 4]);
        Comunas::create(['comuna' => "Vicuña", 'id_ciudad' => 9, 'id_region' => 4]);
        Comunas::create(['comuna' => "Illapel", 'id_ciudad' => 10, 'id_region' => 4]);
        Comunas::create(['comuna' => "Canela", 'id_ciudad' => 10, 'id_region' => 4]);
        Comunas::create(['comuna' => "Los Vilos", 'id_ciudad' => 10, 'id_region' => 4]);
        Comunas::create(['comuna' => "Salamanca", 'id_ciudad' => 10, 'id_region' => 4]);
        Comunas::create(['comuna' => "Ovalle", 'id_ciudad' => 11, 'id_region' => 4]);
        Comunas::create(['comuna' => "Combarbalá", 'id_ciudad' => 11, 'id_region' => 4]);
        Comunas::create(['comuna' => "Monte Patria", 'id_ciudad' => 11, 'id_region' => 4]);
        Comunas::create(['comuna' => "Punitaqui", 'id_ciudad' => 11, 'id_region' => 4]);
        Comunas::create(['comuna' => "Río Hurtado", 'id_ciudad' => 11, 'id_region' => 4]);
        Comunas::create(['comuna' => "Valparaíso", 'id_ciudad' => 12, 'id_region' => 5]);
        Comunas::create(['comuna' => "Casablanca", 'id_ciudad' => 12, 'id_region' => 5]);
        Comunas::create(['comuna' => "Concón", 'id_ciudad' => 12, 'id_region' => 5]);
        Comunas::create(['comuna' => "Juan Fernández", 'id_ciudad' => 12, 'id_region' => 5]);
        Comunas::create(['comuna' => "Puchuncaví", 'id_ciudad' => 12, 'id_region' => 5]);
        Comunas::create(['comuna' => "Quilpué", 'id_ciudad' => 12, 'id_region' => 5]);
        Comunas::create(['comuna' => "Quintero", 'id_ciudad' => 12, 'id_region' => 5]);
        Comunas::create(['comuna' => "Villa Alemana", 'id_ciudad' => 12, 'id_region' => 5]);
        Comunas::create(['comuna' => "Viña del Mar", 'id_ciudad' => 12, 'id_region' => 5]);
        Comunas::create(['comuna' => "Isla de Pascua", 'id_ciudad' => 13, 'id_region' => 5]);
        Comunas::create(['comuna' => "Los Andes", 'id_ciudad' => 14, 'id_region' => 5]);
        Comunas::create(['comuna' => "Calle Larga", 'id_ciudad' => 14, 'id_region' => 5]);
        Comunas::create(['comuna' => "Rinconada", 'id_ciudad' => 14, 'id_region' => 5]);
        Comunas::create(['comuna' => "San Esteban", 'id_ciudad' => 14, 'id_region' => 5]);
        Comunas::create(['comuna' => "La Ligua", 'id_ciudad' => 15, 'id_region' => 5]);
        Comunas::create(['comuna' => "Cabildo", 'id_ciudad' => 15, 'id_region' => 5]);
        Comunas::create(['comuna' => "Papudo", 'id_ciudad' => 15, 'id_region' => 5]);
        Comunas::create(['comuna' => "Petorca", 'id_ciudad' => 15, 'id_region' => 5]);
        Comunas::create(['comuna' => "Zapallar", 'id_ciudad' => 15, 'id_region' => 5]);
        Comunas::create(['comuna' => "Quillota", 'id_ciudad' => 16, 'id_region' => 5]);
        Comunas::create(['comuna' => "Calera", 'id_ciudad' => 16, 'id_region' => 5]);
        Comunas::create(['comuna' => "Hijuelas", 'id_ciudad' => 16, 'id_region' => 5]);
        Comunas::create(['comuna' => "La Cruz", 'id_ciudad' => 16, 'id_region' => 5]);
        Comunas::create(['comuna' => "Limache", 'id_ciudad' => 16, 'id_region' => 5]);
        Comunas::create(['comuna' => "Nogales", 'id_ciudad' => 16, 'id_region' => 5]);
        Comunas::create(['comuna' => "Olmué", 'id_ciudad' => 16, 'id_region' => 5]);
        Comunas::create(['comuna' => "San Antonio", 'id_ciudad' => 17, 'id_region' => 5]);
        Comunas::create(['comuna' => "Algarrobo", 'id_ciudad' => 17, 'id_region' => 5]);
        Comunas::create(['comuna' => "Cartagena", 'id_ciudad' => 17, 'id_region' => 5]);
        Comunas::create(['comuna' => "El Quisco", 'id_ciudad' => 17, 'id_region' => 5]);
        Comunas::create(['comuna' => "El Tabo", 'id_ciudad' => 17, 'id_region' => 5]);
        Comunas::create(['comuna' => "Santo Domingo", 'id_ciudad' => 17, 'id_region' => 5]);
        Comunas::create(['comuna' => "San Felipe", 'id_ciudad' => 18, 'id_region' => 5]);
        Comunas::create(['comuna' => "Catemu", 'id_ciudad' => 18, 'id_region' => 5]);
        Comunas::create(['comuna' => "Llay Llay", 'id_ciudad' => 18, 'id_region' => 5]);
        Comunas::create(['comuna' => "Panquehue", 'id_ciudad' => 18, 'id_region' => 5]);
        Comunas::create(['comuna' => "Putaendo", 'id_ciudad' => 18, 'id_region' => 5]);
        Comunas::create(['comuna' => "Santa María", 'id_ciudad' => 18, 'id_region' => 5]);
        Comunas::create(['comuna' => "Rancagua", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Codegua", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Coinco", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Coltauco", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Doñihue", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Graneros", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Las Cabras", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Machalí", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Malloa", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Mostazal", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Olivar", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Peumo", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Pichidegua", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Quinta de Tilcoco", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Rengo", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Requinoa", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "San Vicente", 'id_ciudad' => 19, 'id_region' => 6]);
        Comunas::create(['comuna' => "Pichilemu", 'id_ciudad' => 20, 'id_region' => 6]);
        Comunas::create(['comuna' => "La Estrella", 'id_ciudad' => 20, 'id_region' => 6]);
        Comunas::create(['comuna' => "Litueche", 'id_ciudad' => 20, 'id_region' => 6]);
        Comunas::create(['comuna' => "Marchihue", 'id_ciudad' => 20, 'id_region' => 6]);
        Comunas::create(['comuna' => "Navidad", 'id_ciudad' => 20, 'id_region' => 6]);
        Comunas::create(['comuna' => "Paredones", 'id_ciudad' => 20, 'id_region' => 6]);
        Comunas::create(['comuna' => "San Fernando", 'id_ciudad' => 21, 'id_region' => 6]);
        Comunas::create(['comuna' => "Chépica", 'id_ciudad' => 21, 'id_region' => 6]);
        Comunas::create(['comuna' => "Chimbarongo", 'id_ciudad' => 21, 'id_region' => 6]);
        Comunas::create(['comuna' => "Lolol", 'id_ciudad' => 21, 'id_region' => 6]);
        Comunas::create(['comuna' => "Nancagua", 'id_ciudad' => 21, 'id_region' => 6]);
        Comunas::create(['comuna' => "Palmilla", 'id_ciudad' => 21, 'id_region' => 6]);
        Comunas::create(['comuna' => "Peralillo", 'id_ciudad' => 21, 'id_region' => 6]);
        Comunas::create(['comuna' => "Placilla", 'id_ciudad' => 21, 'id_region' => 6]);
        Comunas::create(['comuna' => "Pumanque", 'id_ciudad' => 21, 'id_region' => 6]);
        Comunas::create(['comuna' => "Santa Cruz", 'id_ciudad' => 21, 'id_region' => 6]);
        Comunas::create(['comuna' => "Talca", 'id_ciudad' => 22, 'id_region' => 7]);
        Comunas::create(['comuna' => "Constitución", 'id_ciudad' => 22, 'id_region' => 7]);
        Comunas::create(['comuna' => "Curepto", 'id_ciudad' => 22, 'id_region' => 7]);
        Comunas::create(['comuna' => "Empedrado", 'id_ciudad' => 22, 'id_region' => 7]);
        Comunas::create(['comuna' => "Maule", 'id_ciudad' => 22, 'id_region' => 7]);
        Comunas::create(['comuna' => "Pelarco", 'id_ciudad' => 22, 'id_region' => 7]);
        Comunas::create(['comuna' => "Pencahue", 'id_ciudad' => 22, 'id_region' => 7]);
        Comunas::create(['comuna' => "Río Claro", 'id_ciudad' => 22, 'id_region' => 7]);
        Comunas::create(['comuna' => "San Clemente", 'id_ciudad' => 22, 'id_region' => 7]);
        Comunas::create(['comuna' => "San Rafael", 'id_ciudad' => 22, 'id_region' => 7]);
        Comunas::create(['comuna' => "Cauquenes", 'id_ciudad' => 23, 'id_region' => 7]);
        Comunas::create(['comuna' => "Chanco", 'id_ciudad' => 23, 'id_region' => 7]);
        Comunas::create(['comuna' => "Pelluhue", 'id_ciudad' => 23, 'id_region' => 7]);
        Comunas::create(['comuna' => "Curicó", 'id_ciudad' => 24, 'id_region' => 7]);
        Comunas::create(['comuna' => "Hualañé", 'id_ciudad' => 24, 'id_region' => 7]);
        Comunas::create(['comuna' => "Licantén", 'id_ciudad' => 24, 'id_region' => 7]);
        Comunas::create(['comuna' => "Molina", 'id_ciudad' => 24, 'id_region' => 7]);
        Comunas::create(['comuna' => "Rauco", 'id_ciudad' => 24, 'id_region' => 7]);
        Comunas::create(['comuna' => "Romeral", 'id_ciudad' => 24, 'id_region' => 7]);
        Comunas::create(['comuna' => "Sagrada Familia", 'id_ciudad' => 24, 'id_region' => 7]);
        Comunas::create(['comuna' => "Teno", 'id_ciudad' => 24, 'id_region' => 7]);
        Comunas::create(['comuna' => "Vichuquén", 'id_ciudad' => 24, 'id_region' => 7]);
        Comunas::create(['comuna' => "Linares", 'id_ciudad' => 25, 'id_region' => 7]);
        Comunas::create(['comuna' => "Colbún", 'id_ciudad' => 25, 'id_region' => 7]);
        Comunas::create(['comuna' => "Longaví", 'id_ciudad' => 25, 'id_region' => 7]);
        Comunas::create(['comuna' => "Parral", 'id_ciudad' => 25, 'id_region' => 7]);
        Comunas::create(['comuna' => "Retiro", 'id_ciudad' => 25, 'id_region' => 7]);
        Comunas::create(['comuna' => "San Javier", 'id_ciudad' => 25, 'id_region' => 7]);
        Comunas::create(['comuna' => "Villa Alegre", 'id_ciudad' => 25, 'id_region' => 7]);
        Comunas::create(['comuna' => "Yerbas Buenas", 'id_ciudad' => 25, 'id_region' => 7]);
        Comunas::create(['comuna' => "Concepción", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Coronel", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Chiguayante", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Florida", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Hualqui", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Lota", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Penco", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "San Pedro De La Paz", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Santa Juana", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Talcahuano", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Tomé", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Hualpén", 'id_ciudad' => 26, 'id_region' => 8]);
        Comunas::create(['comuna' => "Lebu", 'id_ciudad' => 27, 'id_region' => 8]);
        Comunas::create(['comuna' => "Arauco", 'id_ciudad' => 27, 'id_region' => 8]);
        Comunas::create(['comuna' => "Cañete", 'id_ciudad' => 27, 'id_region' => 8]);
        Comunas::create(['comuna' => "Contulmo", 'id_ciudad' => 27, 'id_region' => 8]);
        Comunas::create(['comuna' => "Curanilahue", 'id_ciudad' => 27, 'id_region' => 8]);
        Comunas::create(['comuna' => "Los Alamos", 'id_ciudad' => 27, 'id_region' => 8]);
        Comunas::create(['comuna' => "Tirua", 'id_ciudad' => 27, 'id_region' => 8]);
        Comunas::create(['comuna' => "Los Angeles", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Antuco", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Cabrero", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Laja", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Mulchén", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Nacimiento", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Negrete", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Quilaco", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Quilleco", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "San Rosendo", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Santa Bárbara", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Tucapel", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Yumbel", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Alto Biobío", 'id_ciudad' => 28, 'id_region' => 8]);
        Comunas::create(['comuna' => "Chillán", 'id_ciudad' => 54, 'id_region' => 16]);
        Comunas::create(['comuna' => "Bulnes", 'id_ciudad' => 54, 'id_region' => 16]);
        Comunas::create(['comuna' => "Cobquecura", 'id_ciudad' => 53, 'id_region' => 16]);
        Comunas::create(['comuna' => "Coelemu", 'id_ciudad' => 53, 'id_region' => 16]);
        Comunas::create(['comuna' => "Coihueco", 'id_ciudad' => 54, 'id_region' => 16]);
        Comunas::create(['comuna' => "Chillán Viejo", 'id_ciudad' => 53, 'id_region' => 16]);
        Comunas::create(['comuna' => "El Carmen", 'id_ciudad' => 54, 'id_region' => 16]);
        Comunas::create(['comuna' => "Ninhue", 'id_ciudad' => 53, 'id_region' => 16]);
        Comunas::create(['comuna' => "Ñiquén", 'id_ciudad' => 55, 'id_region' => 16]);
        Comunas::create(['comuna' => "Pemuco", 'id_ciudad' => 54, 'id_region' => 16]);
        Comunas::create(['comuna' => "Pinto", 'id_ciudad' => 54, 'id_region' => 16]);
        Comunas::create(['comuna' => "Portezuelo", 'id_ciudad' => 53, 'id_region' => 16]);
        Comunas::create(['comuna' => "Quillón", 'id_ciudad' => 54, 'id_region' => 16]);
        Comunas::create(['comuna' => "Quirihue", 'id_ciudad' => 53, 'id_region' => 16]);
        Comunas::create(['comuna' => "Ranquil", 'id_ciudad' => 53, 'id_region' => 16]);
        Comunas::create(['comuna' => "San Carlos", 'id_ciudad' => 55, 'id_region' => 16]);
        Comunas::create(['comuna' => "San Fabián", 'id_ciudad' => 55, 'id_region' => 16]);
        Comunas::create(['comuna' => "San Ignacio", 'id_ciudad' => 54, 'id_region' => 16]);
        Comunas::create(['comuna' => "San Nicolás", 'id_ciudad' => 55, 'id_region' => 16]);
        Comunas::create(['comuna' => "Trehuaco", 'id_ciudad' => 53, 'id_region' => 16]);
        Comunas::create(['comuna' => "Yungay", 'id_ciudad' => 54, 'id_region' => 16]);
        Comunas::create(['comuna' => "Temuco", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Carahue", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Cunco", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Curarrehue", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Freire", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Galvarino", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Gorbea", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Lautaro", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Loncoche", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Melipeuco", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Nueva Imperial", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Padre Las Casas", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Perquenco", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Pitrufquén", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Pucón", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Saavedra", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Teodoro Schmidt", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Toltén", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Vilcún", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Villarrica", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Cholchol", 'id_ciudad' => 29, 'id_region' => 9]);
        Comunas::create(['comuna' => "Angol", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Collipulli", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Curacautín", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Ercilla", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Lonquimay", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Los Sauces", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Lumaco", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Purén", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Renaico", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Traiguén", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Victoria", 'id_ciudad' => 30, 'id_region' => 9]);
        Comunas::create(['comuna' => "Puerto Montt", 'id_ciudad' => 31, 'id_region' => 10]);
        Comunas::create(['comuna' => "Calbuco", 'id_ciudad' => 31, 'id_region' => 10]);
        Comunas::create(['comuna' => "Cochamó", 'id_ciudad' => 31, 'id_region' => 10]);
        Comunas::create(['comuna' => "Fresia", 'id_ciudad' => 31, 'id_region' => 10]);
        Comunas::create(['comuna' => "Frutillar", 'id_ciudad' => 31, 'id_region' => 10]);
        Comunas::create(['comuna' => "Los Muermos", 'id_ciudad' => 31, 'id_region' => 10]);
        Comunas::create(['comuna' => "Llanquihue", 'id_ciudad' => 31, 'id_region' => 10]);
        Comunas::create(['comuna' => "Maullín", 'id_ciudad' => 31, 'id_region' => 10]);
        Comunas::create(['comuna' => "Puerto Varas", 'id_ciudad' => 31, 'id_region' => 10]);
        Comunas::create(['comuna' => "Castro", 'id_ciudad' => 32, 'id_region' => 10]);
        Comunas::create(['comuna' => "Ancud", 'id_ciudad' => 32, 'id_region' => 10]);
        Comunas::create(['comuna' => "Chonchi", 'id_ciudad' => 32, 'id_region' => 10]);
        Comunas::create(['comuna' => "Curaco de Vélez", 'id_ciudad' => 32, 'id_region' => 10]);
        Comunas::create(['comuna' => "Dalcahue", 'id_ciudad' => 32, 'id_region' => 10]);
        Comunas::create(['comuna' => "Puqueldón", 'id_ciudad' => 32, 'id_region' => 10]);
        Comunas::create(['comuna' => "Queilén", 'id_ciudad' => 32, 'id_region' => 10]);
        Comunas::create(['comuna' => "Quellón", 'id_ciudad' => 32, 'id_region' => 10]);
        Comunas::create(['comuna' => "Quemchi", 'id_ciudad' => 32, 'id_region' => 10]);
        Comunas::create(['comuna' => "Quinchao", 'id_ciudad' => 32, 'id_region' => 10]);
        Comunas::create(['comuna' => "Osorno", 'id_ciudad' => 33, 'id_region' => 10]);
        Comunas::create(['comuna' => "Puerto Octay", 'id_ciudad' => 33, 'id_region' => 10]);
        Comunas::create(['comuna' => "Purranque", 'id_ciudad' => 33, 'id_region' => 10]);
        Comunas::create(['comuna' => "Puyehue", 'id_ciudad' => 33, 'id_region' => 10]);
        Comunas::create(['comuna' => "Río Negro", 'id_ciudad' => 33, 'id_region' => 10]);
        Comunas::create(['comuna' => "San Juan de la Costa", 'id_ciudad' => 33, 'id_region' => 10]);
        Comunas::create(['comuna' => "San Pablo", 'id_ciudad' => 33, 'id_region' => 10]);
        Comunas::create(['comuna' => "Chaitén", 'id_ciudad' => 34, 'id_region' => 10]);
        Comunas::create(['comuna' => "Futaleufú", 'id_ciudad' => 34, 'id_region' => 10]);
        Comunas::create(['comuna' => "Hualaihue", 'id_ciudad' => 34, 'id_region' => 10]);
        Comunas::create(['comuna' => "Palena", 'id_ciudad' => 34, 'id_region' => 10]);
        Comunas::create(['comuna' => "Coihaique", 'id_ciudad' => 35, 'id_region' => 11]);
        Comunas::create(['comuna' => "Lago Verde", 'id_ciudad' => 35, 'id_region' => 11]);
        Comunas::create(['comuna' => "Aisén", 'id_ciudad' => 36, 'id_region' => 11]);
        Comunas::create(['comuna' => "Cisnes", 'id_ciudad' => 36, 'id_region' => 11]);
        Comunas::create(['comuna' => "Guaitecas", 'id_ciudad' => 36, 'id_region' => 11]);
        Comunas::create(['comuna' => "Cochrane", 'id_ciudad' => 37, 'id_region' => 11]);
        Comunas::create(['comuna' => "Ohiggins", 'id_ciudad' => 37, 'id_region' => 11]);
        Comunas::create(['comuna' => "Tortel", 'id_ciudad' => 37, 'id_region' => 11]);
        Comunas::create(['comuna' => "Chile Chico", 'id_ciudad' => 38, 'id_region' => 11]);
        Comunas::create(['comuna' => "Río Ibáñez", 'id_ciudad' => 38, 'id_region' => 11]);
        Comunas::create(['comuna' => "Punta Arenas", 'id_ciudad' => 39, 'id_region' => 12]);
        Comunas::create(['comuna' => "Laguna Blanca", 'id_ciudad' => 39, 'id_region' => 12]);
        Comunas::create(['comuna' => "Río Verde", 'id_ciudad' => 39, 'id_region' => 12]);
        Comunas::create(['comuna' => "San Gregorio", 'id_ciudad' => 39, 'id_region' => 12]);
        Comunas::create(['comuna' => "Cabo de Hornos", 'id_ciudad' => 40, 'id_region' => 12]);
        Comunas::create(['comuna' => "Antártica", 'id_ciudad' => 40, 'id_region' => 12]);
        Comunas::create(['comuna' => "Porvenir", 'id_ciudad' => 41, 'id_region' => 12]);
        Comunas::create(['comuna' => "Primavera", 'id_ciudad' => 41, 'id_region' => 12]);
        Comunas::create(['comuna' => "Timaukel", 'id_ciudad' => 41, 'id_region' => 12]);
        Comunas::create(['comuna' => "Natales", 'id_ciudad' => 42, 'id_region' => 12]);
        Comunas::create(['comuna' => "Torres del Paine", 'id_ciudad' => 42, 'id_region' => 12]);
        Comunas::create(['comuna' => "Santiago", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Cerrillos", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Cerro Navia", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Conchalí", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "El Bosque", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Estación Central", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Huechuraba", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Independencia", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "La Cisterna", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "La Florida", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "La Granja", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "La Pintana", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "La Reina", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Las Condes", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Lo Barnechea", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Lo Espejo", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Lo Prado", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Macul", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Maipú", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Ñuñoa", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Pedro Aguirre Cerda", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Peñalolén", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Providencia", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Pudahuel", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Quilicura", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Quinta Normal", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Recoleta", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Renca", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "San Joaquín", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "San Miguel", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "San Ramón", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Vitacura", 'id_ciudad' => 43, 'id_region' => 13]);
        Comunas::create(['comuna' => "Puente Alto", 'id_ciudad' => 44, 'id_region' => 13]);
        Comunas::create(['comuna' => "Pirque", 'id_ciudad' => 44, 'id_region' => 13]);
        Comunas::create(['comuna' => "San José de Maipo", 'id_ciudad' => 44, 'id_region' => 13]);
        Comunas::create(['comuna' => "Colina", 'id_ciudad' => 45, 'id_region' => 13]);
        Comunas::create(['comuna' => "Lampa", 'id_ciudad' => 45, 'id_region' => 13]);
        Comunas::create(['comuna' => "Til til", 'id_ciudad' => 45, 'id_region' => 13]);
        Comunas::create(['comuna' => "San Bernardo", 'id_ciudad' => 46, 'id_region' => 13]);
        Comunas::create(['comuna' => "Buin", 'id_ciudad' => 46, 'id_region' => 13]);
        Comunas::create(['comuna' => "Calera de Tango", 'id_ciudad' => 46, 'id_region' => 13]);
        Comunas::create(['comuna' => "Paine", 'id_ciudad' => 46, 'id_region' => 13]);
        Comunas::create(['comuna' => "Melipilla", 'id_ciudad' => 47, 'id_region' => 13]);
        Comunas::create(['comuna' => "Alhué", 'id_ciudad' => 47, 'id_region' => 13]);
        Comunas::create(['comuna' => "Curacaví", 'id_ciudad' => 47, 'id_region' => 13]);
        Comunas::create(['comuna' => "María Pinto", 'id_ciudad' => 47, 'id_region' => 13]);
        Comunas::create(['comuna' => "San Pedro", 'id_ciudad' => 47, 'id_region' => 13]);
        Comunas::create(['comuna' => "Talagante", 'id_ciudad' => 48, 'id_region' => 13]);
        Comunas::create(['comuna' => "El Monte", 'id_ciudad' => 48, 'id_region' => 13]);
        Comunas::create(['comuna' => "Isla de Maipo", 'id_ciudad' => 48, 'id_region' => 13]);
        Comunas::create(['comuna' => "Padre Hurtado", 'id_ciudad' => 48, 'id_region' => 13]);
        Comunas::create(['comuna' => "Peñaflor", 'id_ciudad' => 48, 'id_region' => 13]);
        Comunas::create(['comuna' => "Valdivia", 'id_ciudad' => 49, 'id_region' => 14]);
        Comunas::create(['comuna' => "Corral", 'id_ciudad' => 49, 'id_region' => 14]);
        Comunas::create(['comuna' => "Lanco", 'id_ciudad' => 49, 'id_region' => 14]);
        Comunas::create(['comuna' => "Los Lagos", 'id_ciudad' => 49, 'id_region' => 14]);
        Comunas::create(['comuna' => "Máfil", 'id_ciudad' => 49, 'id_region' => 14]);
        Comunas::create(['comuna' => "Mariquina", 'id_ciudad' => 49, 'id_region' => 14]);
        Comunas::create(['comuna' => "Paillaco", 'id_ciudad' => 49, 'id_region' => 14]);
        Comunas::create(['comuna' => "Panguipulli", 'id_ciudad' => 49, 'id_region' => 14]);
        Comunas::create(['comuna' => "La Unión", 'id_ciudad' => 50, 'id_region' => 14]);
        Comunas::create(['comuna' => "Futrono", 'id_ciudad' => 50, 'id_region' => 14]);
        Comunas::create(['comuna' => "Lago Ranco", 'id_ciudad' => 50, 'id_region' => 14]);
        Comunas::create(['comuna' => "Río Bueno", 'id_ciudad' => 50, 'id_region' => 14]);
        Comunas::create(['comuna' => "Arica", 'id_ciudad' => 51, 'id_region' => 15]);
        Comunas::create(['comuna' => "Camarones", 'id_ciudad' => 51, 'id_region' => 15]);
        Comunas::create(['comuna' => "Putre", 'id_ciudad' => 52, 'id_region' => 15]);
        Comunas::create(['comuna' => "General Lagos", 'id_ciudad' => 52, 'id_region' => 15]);

        Comentarios::create(['id_comentario'=>1,'estado'=>1,'comentario'=>"Sin Stock"]);
        Comentarios::create(['id_comentario'=>2,'estado'=>1,'comentario'=>"Sala Cerrada"]);
        Comentarios::create(['id_comentario'=>3,'estado'=>1,'comentario'=>"Sala en remodelacion"]);
        Comentarios::create(['id_comentario'=>4,'estado'=>1,'comentario'=>"Sala rechaza servicio"]);
        Comentarios::create(['id_comentario'=>5,'estado'=>1,'comentario'=>"Servicio realizado por otro proveedor"]);
        Comentarios::create(['id_comentario'=>6,'estado'=>1,'comentario'=>"Elemento no aplican en local"]);
        Comentarios::create(['id_comentario'=>7,'estado'=>1,'comentario'=>"Se reagenda servicio por horario"]);
        Comentarios::create(['id_comentario'=>8,'estado'=>1,'comentario'=>"Se reagenda por falta de elementos"]);
        Comentarios::create(['id_comentario'=>9,'estado'=>1,'comentario'=>"Mueble con desperfecto"]);
        Comentarios::create(['id_comentario'=>10,'estado'=>1,'comentario'=>"Otros"]);

    }
}

